  steps:
  # Build the container image
  - name: 'gradle'
    entrypoint: 'gradle'
    args:
      - 'clean'
      - 'bootWar'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/koalaserver/cloud-run-source-deploy/koala-attendance-server/koala-server@sha256:$COMMIT_SHA'
      - '.'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/koalaserver/cloud-run-source-deploy/koala-attendance-server/koala-server@sha256:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'koala-server'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/koalaserver/cloud-run-source-deploy/koala-attendance-server/koala-server@sha256:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
  images:
  - 'asia-northeast1-docker.pkg.dev/koalaserver/cloud-run-source-deploy/koala-attendance-server/koala-server@sha256:$COMMIT_SHA'

